# Generated by Django 4.2.1 on 2023-05-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('emails', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('role', models.CharField(default='student', max_length=20)),
            ],
        ),
    ]
