# Generated by Django 4.2.1 on 2023-05-10 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_emails_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('deadLine', models.DateTimeField(default=datetime.datetime(2023, 5, 20, 15, 35, 34, 508327))),
            ],
        ),
    ]
